rules = [
  RemoveUnused,
  ExplicitResultTypes,
  ProcedureSyntax,
  OrganizeImports
]

RemoveUnused.imports = false
OrganizeImports.groupedImports = Merge
OrganizeImports.importSelectorsOrder = SymbolsFirst
OrganizeImports.groups = [
  "re:javax?\\.",
  "scala.",
  "java.",
  "org.slf4j.",
  "org.apache.kafka.",
  "io.confluent.",
  "com.sksamuel.avro4s.",
  "*",
  "com.andy327.kl."
]
